apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino-client.fullname" . }}-sh-configmap
  labels:
    {{- include "trino-client.labels" . | nindent 4 }}
data:

  client.sh: |
    /opt/app/trino --debug --user=admin --password --truststore-path=/opt/trino/certs/truststore.jks --truststore-password=password --server https://coordinator-headless:8443
    
    
