apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coordinator.fullname" . }}-password-secret
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}   

type: Opaque
data:
  password.db: |
    dGVzdDokMnkkMTAkOWxhckZsSGR5YXo1eGJSb00zZlBBdXJCQUdUdm9JMVhxN0pKT2xoNE12c2ZkYnd4b091bGEKc2toYXRyaTokMnkkMTAkZm5PLldnd2VoWkVuUWlyTU1zdzEvdVY0aFNsS2pLekVJOGgubHNCU09NTGFBY1MxT0YzYk8KYWRtaW46JDJ5JDEwJDJQQjV0Y2czNDIwTXJVSTQyYmdJcU94RG5pMlBSOEdtZVg3L1BDNkVRRjZwZkY0ZW5HbmJTCg==
