apiVersion: v1
kind: Service
metadata:
  name: {{ include "coordinator.fullname" . }}-headless
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.httpport }}
      targetPort: httpport
      protocol: TCP
      name: httpport
  selector:
    {{- include "coordinator.selectorLabels" . | nindent 4 }}
  clusterIP: None