apiVersion: v1
kind: Service
metadata:
  name: {{ include "coordinator.fullname" . }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tlsport }}
      targetPort: tlsport
      protocol: TCP
      name: tlsport
  selector:
    {{- include "coordinator.selectorLabels" . | nindent 4 }}
