apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive
  labels:
    app: hive
spec:
  serviceName: hive
  replicas: 1
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      containers:
      - name: hive
        imagePullPolicy: IfNotPresent
        image: "192.168.64.1:5000/skhatri/hive:0.2"
        ports:
        - name: thriftport
          containerPort: 8093
        - name: hiveport
          containerPort: 10000

        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi  
        env:

        - name: AIRFLOW__KUBERNETES__IN_CLUSTER
          value: "True"


        volumeMounts:
        - mountPath: /opt/airflow/dags
          name: airflow-dags
      volumes:
      - name: secrets-mount
        secret:
          secretName: airflow-secrets
          items:
          - key: GIT_TOKEN
            path: git_token
      - name: airflow-dags
        emptyDir: {}
         
---
kind: Service
apiVersion: v1
metadata:
  name: hive
spec:
  selector:
    app: hive
  ports:
  - name: thriftport
    protocol: TCP
    port: 8093
    targetPort: thriftport
  - name: hiveport
    protocol: TCP
    port: 10000
    targetPort: hiveport    
  type: ClusterIP
