apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
  labels:
    app: coordinator
spec:
  serviceName: coordinator
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      hostname: coordinator
      containers:
      - name: coordinator
        imagePullPolicy: IfNotPresent
        image: "192.168.64.1:5000/trinodb/trino:352"
        ports:
        - name: httpport
          containerPort: 8080
        - name: tlsport
          containerPort: 8443

        resources:
          requests:
            cpu: 200m
            memory: 1400Mi  
        env:

        - name: ENVIRONMENT
          value: "development"


        volumeMounts:
        - mountPath: /etc/trino/catalog
          name: catalog-config-mount
        - mountPath: /etc/trino
          name: config-mount
        - mountPath: /opt/trino/security/rules
          name: rule-secret-mount
        - mountPath: /opt/trino/security/passwords
          name: password-secret-mount          
        - mountPath: /opt/trino/certs
          name: cert-secret-mount  
        - mountPath: /data/trino
          name: data-dir

      volumes:
      - name: config-mount
        configMap:
          name: coordinator-configmap
      - name: catalog-config-mount
        configMap:
          name: coordinator-catalog-configmap
      - name: rule-secret-mount
        secret:
          secretName: coordinator-rule-secret
      - name: password-secret-mount
        secret:
          secretName: coordinator-password-secret
      - name: cert-secret-mount
        secret:
          secretName: coordinator-cert-secret
      - name: data-dir
        emptyDir: {}
         
---
kind: Service
apiVersion: v1
metadata:
  name: coordinator
spec:
  selector:
    app: coordinator
  ports:
  - name: tlsport
    protocol: TCP
    port: 8443
    targetPort: tlsport
    nodePort: 32538    
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: coordinator-headless
spec:
  selector:
    app: coordinator
  ports:
  - name: httpport
    protocol: TCP
    port: 8080
    targetPort: httpport
  clusterIP: None