apiVersion: "v1"
kind: ConfigMap
metadata:
  name: coordinator-catalog-configmap
  labels:
    role: coordinator
data:
  memory.properties: |
    connector.name=memory
  jmx.properties: |
    connector.name=jmx
  tpcds.properties: |
    connector.name=tpcds
    tpcds.split-per-node=4
  tpch.properties: |
    connector.name=tpch
    tpch.split-per-node=4
