apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-secret
  labels:
    {{- include "superset.labels" . | nindent 4 }}
type: Opaque
data:

  SQLALCHEMY_DATABASE_URI: {{ .Values.sqlalchemy.databaseUri |b64enc }}

    
