
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-catalog-configmap
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  memory.properties: |
    connector.name=memory
{{- if .Values.catalog -}}    
  jmx.properties: |
    connector.name=jmx
  tpcds.properties: |
    connector.name=tpcds
    tpcds.split-per-node=4
  tpch.properties: |
    connector.name=tpch
    tpch.split-per-node=4
{{- end }}
