apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: worker
spec:
  serviceName: worker
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        imagePullPolicy: IfNotPresent
        image: "192.168.64.1:5000/trinodb/trino:352"
        ports:
        - name: httpport
          containerPort: 8080
        - name: tlsport
          containerPort: 8443

        resources:
          requests:
            cpu: 200m
            memory: 1400Mi  
        env:

        - name: ENVIRONMENT
          value: "development"

        command:
          - /bin/sh
        args:
          - -c
          - /opt/trino/init/init.sh

        volumeMounts:
        - mountPath: /tmp/catalog
          name: catalog-config-mount
        - mountPath: /tmp/main
          name: config-mount
        - mountPath: /opt/trino/certs
          name: cert-secret-mount  
        - mountPath: /data/trino
          name: data-dir
        - mountPath: /etc/trino
          name: config-dir
        - mountPath: /opt/trino/init
          name: initialiser-config-mount
      
      nodeSelector: {}

      volumes:
      - name: config-mount
        configMap:
          name: worker-configmap
      - name: catalog-config-mount
        configMap:
          name: worker-catalog-configmap
      - name: cert-secret-mount
        secret:
          secretName: worker-cert-secret
      - name: initialiser-config-mount
        configMap:
          name: worker-initialiser-config
          defaultMode: 0755
      - name: data-dir
        emptyDir: {}
      - name: config-dir
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
  - name: httpport
    protocol: TCP
    port: 8080
    targetPort: httpport
  type: ClusterIP
