apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-configmap
  labels:
    {{- include "hive.labels" . | nindent 4 }}    
data:

  hive-site.xml: |-
    {{ .Files.Get "hive-site-template.xml" | b64enc | indent 4 }}

  parquet-logging.properties: |-
    {{ .Files.Get "parquet-logging.properties" | b64enc | indent 4}}