{{- if .Values.secret.s3.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}-s3-secret
  labels:
    {{- include "hive.labels" . | nindent 4 }}    
type: Opaque

data:

  AWS_ACCESS_KEY_ID: {{ .Values.secret.s3.access_key_id |b64enc }}

  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.s3.secret_access_key |b64enc}}
{{- end }}