apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-init-scripts-configmap
  labels:
    {{- include "hive.labels" . | nindent 4 }}    

data:

  init.sh: |
    #!/usr/bin/env bash
    mkdir -p /tmp/hive
    chmod 777 /tmp/hive
    if [[ -d /opt/app/conf-data ]];
    then
      for x in $(ls /opt/app/conf-data);
      do
        echo copying /opt/app/conf-data/$x
        base64 --decode /opt/app/conf-data/$x > /opt/app/apache-hive-3.1.2-bin/conf/$x
      done;
    fi;
