apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.hiveport }}
      targetPort: hiveport
      protocol: TCP
      name: hiveport
    - name: thriftport
      protocol: TCP
      port: {{ .Values.service.thriftport }}
      targetPort: thriftport
      
  selector:
    {{- include "hive.selectorLabels" . | nindent 4 }}

